platform :ios, '11.0'

target '__PRODUCT_NAME__' do
  use_frameworks!

  # Pods for __PRODUCT_NAME__
  # NOTE: This must match the dependencies listed in __PRODUCT_NAME__.podspec.

  # We define the dependencies in the Podspec so they are pulled in when
  # integrating __PRODUCT_NAME__ via CocoaPods.
  # We define the dependencies here so they are pulled in to the project/workspace
  # during development.

  target '__PRODUCT_NAME__Tests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target '__PRODUCT_NAME__Example' do
  use_frameworks!

  # Pods for __PRODUCT_NAME__Example

  # Because __PRODUCT_NAME__ uses CocoaPods to resolve its dependencies, we
  # need to include it via CocoaPods even though it lives in the same
  # project/workspace as the example project.
  pod '__PRODUCT_NAME__', :path => '.'
end

